[package]
name = "gregor"
version = "0.3.2"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
description = "Simple implementation of the Gregorian calendar."
repository = "https://github.com/SimonSapin/gregor"
license = "MIT"
build = "build.rs"

[features]
system_time = []
